apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-halls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-halls
  template:
    metadata:
      labels:
        app: cinema-halls
    spec:
      containers:
        - image: myfirstmolly/hallservice
          name: cinema-halls
          ports:
            - containerPort: 8083
              name: cinema-halls
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.101:5432/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"